defaults:
  - train_transform: simple
  - test_transform: simple

name: advanced_prompts_augmented
num_classes: 37
batch_size: 128
num_workers: 8
train_path: ${data_dir}/train/advanced_prompts_augmented
real_images_val_path: ${data_dir}/val
test_path: ${data_dir}/test
