defaults:
  - train_transform: simple
  - test_transform: simple

name: gpt_prompts
num_classes: 37
batch_size: 128
num_workers: 8
real_images_val_path: ${data_dir}/val
test_path: ${data_dir}/test
train_path: ${data_dir}/train/gpt-prompts-2_augmented
