defaults:
  - model: dinov2base
  - dataset: test_prompts
  - optim: adamw
  - loss_fn: cross_entropy
  - scheduler: null

epochs: 5

datamodule:
  _target_: data.datamodule.DataModule
  train_dataset_path: ${dataset.train_path}
  real_images_val_path: ${dataset.real_images_val_path}
  train_transform: ${dataset.train_transform}
  val_transform: ${dataset.test_transform}
  batch_size: ${dataset.batch_size}
  num_workers: ${dataset.num_workers}

data_dir: ${root_dir}/dataset
root_dir:  ${hydra:runtime.cwd}
checkpoint_path: ${root_dir}/checkpoints/${experiment_name}.pt
nb_repeats: 1

experiment_name: ${model.name}_${dataset.name}
ocr_method: 'easyocr' # To choose the ocr method
comparison_method: 'fuzzywuzzy'  # or 'difflib'
threshold_ocr: 0.8  # Threshold for the ocr method
increment: 0.05  # Increment for the threshold

hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}/
  job:
    chdir: true